### PR TITLE
Python 3 Migration

### PR DESCRIPTION
**Pull request by MRichards99**
This PR allows ICAT Ansible to run in Python 2 & 3. The main changes for this are reverting back to `./setup` where `python2` has been forced, and bumping version numbers for ICAT components where the Python code has been migrated to work with Python 3.

### CODE REVIEW

**Comment by MRichards99** [comment]
This PR has now run on GitHub Actions, where the default Python version is Python 3. I think this is enough testing that I can say that this repo works on Python 3

**Comment by MRichards99** [comment]
I've also added a name to the CI job because I missed that from #74 

This PR is ready for review now

**Comment by MRichards99** [comment]
Found a problem on RedHat machines when using Python 3 (see #52). Back to draft..

**Comment by MRichards99** [comment]
#52 has been resolved/closed so I'm putting this PR back to ready for review because there are no more changes that need to be made.

**Review by VKTB — APPROVED** [review]

**Pull request merged**
